CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255),
  username VARCHAR(100),
  google_id VARCHAR(255),
  profile_pic VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);